### PR TITLE
Get postcode data from wikipedia

### PR DESCRIPTION
**Pull request by lepture**
Use wikipedia data for now.

https://github.com/cn/GB2260/issues/19

### CODE REVIEW

**Comment by lepture** [comment]
ping @cn/programmers

**Comment by gaomd** [comment]
What's the use of postal code in this project?

**Comment by lepture** [comment]
@gaomd 通过 code 获取 postcode

**Comment by lepture** [comment]
之后也许还会添加别的，作为补充，可实现可不实现。

**Comment by lepture** [comment]
Not a part of GB2260. Make it another repo.

**Pull request closed without merging**
